const LESSONS = [
  {
    id: "greetings",
    title: "Greetings",
    icon: "👋",
    color: "#58CC02",
    description: "Hello, goodbye, and everyday courtesies",
    words: [
      { persian: "سلام", phonetic: "Salaam", english: "Hello", example: "سلام! چطوری؟" },
      { persian: "خدا", phonetic: "Khodaa", english: "God", example: "خدا حافظت باشه." },
      { persian: "حافظ", phonetic: "Haafez", english: "Protector / Memorizer", example: "حافظ شیرازی شاعر بزرگیه." },
      { persian: "خداحافظ", phonetic: "Khodaa Haafez", english: "Goodbye (lit: May God protect you)", example: "خداحافظ! فردا می‌بینمت." },
      { persian: "صبح به خیر", phonetic: "Sob Bekheyr", english: "Good Morning", example: "صبح به خیر! خوب خوابیدی؟" },
      { persian: "شب به خیر", phonetic: "Shab Bekheyr", english: "Good Night", example: "شب به خیر، خواب خوش." },
      { persian: "خوش اومدید", phonetic: "Khosh Umadid", english: "Welcome (lit: You came well)", example: "خوش اومدید به خونه‌مون." },
      { persian: "خوشبختم", phonetic: "Khoshbakhtam", english: "Nice to meet you (lit: I'm fortunate)", example: "خوشبختم از آشناییتون." },
      { persian: "ممنون", phonetic: "Mamnoon", english: "Thank You / Grateful", example: "ممنون از کمکت." },
      { persian: "خواهش میکنم", phonetic: "Khaahesh Mikonam", english: "You're Welcome (lit: I beg you to stop)", example: "خواهش میکنم، مشکلی نیست." },
      { persian: "لطفاً", phonetic: "Lotfan", english: "Please", example: "لطفاً صبر کن." },
      { persian: "ببخشید", phonetic: "Bebakhshid", english: "Sorry / Excuse Me", example: "ببخشید، می‌تونید کمک کنید؟" },
      { persian: "باشه", phonetic: "Baashe", english: "Okay", example: "باشه، بریم." },
      { persian: "بفرمایید", phonetic: "Befarmaaeid", english: "Here You Go / Go Ahead", example: "بفرمایید، بفرمایید، بنشینید." },
    ],
  },
  {
    id: "expressions",
    title: "Expressions",
    icon: "🥂",
    color: "#FF9600",
    description: "Toasts, celebrations, and everyday phrases",
    words: [
      { persian: "سلامتی", phonetic: "Salaamati", english: "Cheers / Health", example: "سلامتی! به سلامت همه." },
      { persian: "نوش جان", phonetic: "Nooshe Jaan", english: "Bon Appétit (lit: May your soul enjoy it)", example: "نوش جان! غذا خوشمزه‌ست." },
      { persian: "خسته نباشی", phonetic: "Khaste Nabashi", english: "Good Job / Hang In There (lit: May you not be tired)", example: "خسته نباشی، کار خوبی کردی." },
      { persian: "تولدت مبارک", phonetic: "Tavalodet Mobarak", english: "Happy Birthday", example: "تولدت مبارک عزیزم!" },
      { persian: "چطوری؟", phonetic: "Chetori?", english: "How Are You? (informal)", example: "سلام! چطوری؟" },
      { persian: "خوبم", phonetic: "Khubam", english: "I'm Well", example: "خوبم، ممنون. تو چطوری؟" },
      { persian: "خوب", phonetic: "Khoob", english: "Good / Well", example: "امروز خوبه." },
      { persian: "بد", phonetic: "Bad", english: "Bad", example: "حالم بده." },
      { persian: "نمی‌فهمم", phonetic: "Nemifahmam", english: "I don't understand", example: "ببخشید، نمی‌فهمم." },
      { persian: "فارسی بلدی؟", phonetic: "Faarsi boladi?", english: "Do you know Persian?", example: "فارسی بلدی؟" },
      { persian: "کمی فارسی بلدم", phonetic: "Kami Faarsi baladam", english: "I know a little Persian", example: "کمی فارسی بلدم." },
      { persian: "موفق باشی", phonetic: "Movaffaq baashi", english: "Good Luck", example: "موفق باشی تو امتحان." },
    ],
  },
  {
    id: "numbers",
    title: "Numbers",
    icon: "🔢",
    color: "#1CB0F6",
    description: "Count and use numbers",
    words: [
      { persian: "یک", phonetic: "Yek", english: "One", example: "یک سیب دارم." },
      { persian: "دو", phonetic: "Do", english: "Two", example: "دو تا بده." },
      { persian: "سه", phonetic: "Se", english: "Three", example: "سه روز دیگه." },
      { persian: "چهار", phonetic: "Chahaar", english: "Four", example: "چهار نفر اومدن." },
      { persian: "پنج", phonetic: "Panj", english: "Five", example: "پنج دقیقه صبر کن." },
      { persian: "شش", phonetic: "Shesh", english: "Six", example: "شش ماه گذشت." },
      { persian: "هفت", phonetic: "Haft", english: "Seven", example: "هفت روز هفته." },
      { persian: "هشت", phonetic: "Hasht", english: "Eight", example: "هشت ساعت خوابیدم." },
      { persian: "نه", phonetic: "Noh", english: "Nine", example: "نه نفر بودیم." },
      { persian: "ده", phonetic: "Dah", english: "Ten", example: "ده دقیقه دیگه." },
      { persian: "بیست", phonetic: "Bist", english: "Twenty", example: "بیست سال دارم." },
      { persian: "صد", phonetic: "Sad", english: "One Hundred", example: "صد تا بخر." },
    ],
  },
  {
    id: "colors",
    title: "Colors",
    icon: "🎨",
    color: "#CE82FF",
    description: "Learn all the colors",
    words: [
      { persian: "قرمز", phonetic: "Ghermez", english: "Red", example: "گل قرمز زیباست." },
      { persian: "آبی", phonetic: "Aabi", english: "Blue", example: "آسمان آبیه." },
      { persian: "سبز", phonetic: "Sabz", english: "Green", example: "درخت سبزه." },
      { persian: "زرد", phonetic: "Zard", english: "Yellow", example: "خورشید زرده." },
      { persian: "سفید", phonetic: "Sefid", english: "White", example: "برف سفیده." },
      { persian: "مشکی", phonetic: "Meshki", english: "Black", example: "شب مشکیه." },
      { persian: "نارنجی", phonetic: "Naaranji", english: "Orange", example: "پرتقال نارنجیه." },
      { persian: "بنفش", phonetic: "Banafsh", english: "Purple", example: "گل بنفشه." },
      { persian: "صورتی", phonetic: "Surati", english: "Pink", example: "لباس صورتیه." },
      { persian: "قهوه‌ای", phonetic: "Ghahve'i", english: "Brown", example: "خاک قهوه‌اییه." },
      { persian: "خاکستری", phonetic: "Khaakestari", english: "Gray", example: "ابر خاکستریه." },
    ],
  },
  {
    id: "family",
    title: "Family",
    icon: "👨‍👩‍👧",
    color: "#FF4B4B",
    description: "Family members — formal and informal",
    words: [
      { persian: "مامان", phonetic: "Maamaan", english: "Mom (informal)", example: "مامان، کجایی؟" },
      { persian: "مادر", phonetic: "Maadar", english: "Mother (formal)", example: "مادرم خوبه." },
      { persian: "بابا", phonetic: "Baabaa", english: "Dad (informal)", example: "بابا، بریم؟" },
      { persian: "پدر", phonetic: "Pedar", english: "Father (formal)", example: "پدرم کار می‌کنه." },
      { persian: "داداش", phonetic: "Daadaash", english: "Bro / Brother (informal)", example: "داداشم خونه‌ست." },
      { persian: "برادر", phonetic: "Baraadar", english: "Brother (formal)", example: "برادرم بزرگه." },
      { persian: "آبجی", phonetic: "Aabji", english: "Sis / Sister (informal)", example: "آبجیم دانشجوئه." },
      { persian: "خواهر", phonetic: "Khaahar", english: "Sister (formal)", example: "خواهرم مهربونه." },
      { persian: "بچه", phonetic: "Bache", english: "Baby / Child", example: "بچه‌ام خوابه." },
      { persian: "دختر", phonetic: "Dokhtar", english: "Girl / Daughter", example: "دختر کوچیکم." },
      { persian: "پسر", phonetic: "Pesar", english: "Boy / Son", example: "پسر باهوشیه." },
      { persian: "مادربزرگ", phonetic: "Maadarbozorg", english: "Grandmother", example: "مادربزرگم مهربونه." },
    ],
  },
  {
    id: "relationships",
    title: "Relationships",
    icon: "💑",
    color: "#FF4B4B",
    description: "Love, friendship, and romance",
    words: [
      { persian: "دوست", phonetic: "Doost", english: "Friend", example: "دوستم خوبه." },
      { persian: "دوست پسر", phonetic: "Doost Pesar", english: "Boyfriend (lit: boy friend)", example: "دوست پسرم ایرانیه." },
      { persian: "دوست دختر", phonetic: "Doost Dokhtar", english: "Girlfriend (lit: girl friend)", example: "دوست دخترم خوشگله." },
      { persian: "عشق", phonetic: "Eshgh", english: "Love", example: "عشق قشنگترین چیزه." },
      { persian: "دوست دارم", phonetic: "Dooset Daaram", english: "I love you (softer, everyday)", example: "دوستت دارم مامان." },
      { persian: "عاشقتم", phonetic: "Aasheghetam", english: "I love you (stronger, romantic)", example: "عاشقتم، نمی‌تونم بدون تو باشم." },
      { persian: "عزیزم", phonetic: "Azizam", english: "My Dear (term of endearment)", example: "عزیزم، حالت خوبه؟" },
      { persian: "عشقم", phonetic: "Eshgham", english: "My Love", example: "عشقم، دلم برات تنگ شده." },
      { persian: "خوشگل", phonetic: "Khoshgel", english: "Pretty / Beautiful", example: "چقدر خوشگلی امروز!" },
      { persian: "خوشتیپ", phonetic: "Khoshtip", english: "Handsome", example: "دوست پسرت خیلی خوشتیپه." },
    ],
  },
  {
    id: "food",
    title: "Food & Drink",
    icon: "🍽️",
    color: "#58CC02",
    description: "Essential food and drink vocabulary",
    words: [
      { persian: "غذا", phonetic: "Ghazaa", english: "Food", example: "غذا حاضره؟" },
      { persian: "آب", phonetic: "Aab", english: "Water", example: "آب بده لطفاً." },
      { persian: "نان", phonetic: "Naan", english: "Bread", example: "نان تازه می‌خوام." },
      { persian: "چای", phonetic: "Chaai", english: "Tea", example: "چای می‌خوری؟" },
      { persian: "قهوه", phonetic: "Ghahve", english: "Coffee", example: "قهوه یا چای؟" },
      { persian: "برنج", phonetic: "Berenj", english: "Rice", example: "برنج ایرانی خوشمزه‌ست." },
      { persian: "مرغ", phonetic: "Morgh", english: "Chicken", example: "مرغ کباب کردیم." },
      { persian: "گوشت", phonetic: "Gusht", english: "Meat", example: "گوشت گرونه." },
      { persian: "میوه", phonetic: "Mive", english: "Fruit", example: "میوه می‌خوری؟" },
      { persian: "پنیر", phonetic: "Panir", english: "Cheese", example: "پنیر و نان." },
      { persian: "تخم مرغ", phonetic: "Tokhm-e morgh", english: "Egg", example: "تخم مرغ آب‌پز." },
      { persian: "شیر", phonetic: "Shir", english: "Milk", example: "شیر گرم بده." },
    ],
  },
  {
    id: "questions",
    title: "Question Words",
    icon: "❓",
    color: "#FF9600",
    description: "Ask anything with these essential words",
    words: [
      { persian: "چی؟", phonetic: "Chi?", english: "What?", example: "چی گفتی؟" },
      { persian: "کجا؟", phonetic: "Kojaa?", english: "Where?", example: "کجا میری؟" },
      { persian: "کی؟", phonetic: "Key?", english: "When? (pronounced 'kay')", example: "کی میای؟" },
      { persian: "کی؟", phonetic: "Ki?", english: "Who?", example: "کی اومد؟" },
      { persian: "چرا؟", phonetic: "Cheraa?", english: "Why?", example: "چرا نیومدی؟" },
      { persian: "چطور؟", phonetic: "Chetor?", english: "How?", example: "این کار رو چطور کردی؟" },
      { persian: "چقدر؟", phonetic: "Cheghad?", english: "How much? / How many?", example: "این چقدره؟" },
      { persian: "کدوم؟", phonetic: "Kodoom?", english: "Which?", example: "کدوم رو می‌خوای؟" },
      { persian: "چند؟", phonetic: "Chand?", english: "How many? / A few", example: "چند تا؟" },
      { persian: "اسمت چیه؟", phonetic: "Esmat chiye?", english: "What's your name?", example: "سلام! اسمت چیه؟" },
    ],
  },
  {
    id: "pronouns",
    title: "Pronouns",
    icon: "👤",
    color: "#1CB0F6",
    description: "I, you, we, they — the building blocks",
    words: [
      { persian: "من", phonetic: "Man", english: "I / Me / My", example: "من ایرانی هستم." },
      { persian: "تو", phonetic: "To", english: "You (singular, informal) — pronounced 'toe'", example: "تو کجایی؟" },
      { persian: "او", phonetic: "Oo", english: "He / She / Him / Her", example: "او خوبه." },
      { persian: "ما", phonetic: "Maa", english: "We / Us", example: "ما با هم رفتیم." },
      { persian: "شما", phonetic: "Shomaa", english: "You (plural or formal)", example: "شما چطورید؟" },
      { persian: "آن ها", phonetic: "Aan Haa", english: "They / Their", example: "آن ها اومدن." },
      { persian: "این", phonetic: "In", english: "This", example: "این چیه؟" },
      { persian: "آن", phonetic: "Aan", english: "That", example: "آن رو بده." },
      { persian: "ها", phonetic: "Haa", english: "Plural marker (like -s in English)", example: "کتاب‌ها کجاست؟" },
    ],
  },
  {
    id: "home-life",
    title: "Home & Daily Life",
    icon: "🏠",
    color: "#CE82FF",
    description: "Your home, free time, and everyday things",
    words: [
      { persian: "خانه", phonetic: "Khaane", english: "House / Home", example: "بریم خونه." },
      { persian: "پول", phonetic: "Pool", english: "Money", example: "پول ندارم." },
      { persian: "کار", phonetic: "Kar", english: "Work / Job", example: "کارم خوبه." },
      { persian: "وقت", phonetic: "Vaght", english: "Time", example: "وقت ندارم." },
      { persian: "خواب", phonetic: "Khaab", english: "Sleep", example: "خوابم میاد." },
      { persian: "رویا", phonetic: "Roya", english: "Dream", example: "رویای قشنگی دیدم." },
      { persian: "فیلم", phonetic: "Film", english: "Movie", example: "فیلم می‌بینیم؟" },
      { persian: "سریال", phonetic: "Serial", english: "TV Show", example: "سریال ایرانی می‌بینم." },
      { persian: "مبل", phonetic: "Mobl", english: "Couch", example: "روی مبل نشستم." },
      { persian: "تخت", phonetic: "Takht", english: "Bed", example: "تخت راحته." },
      { persian: "گربه", phonetic: "Gorbe", english: "Cat", example: "گربه‌ام ناز‌ه." },
      { persian: "سگ", phonetic: "Sag", english: "Dog", example: "سگم باهوشه." },
    ],
  },
  {
    id: "getting-around",
    title: "Getting Around",
    icon: "✈️",
    color: "#1CB0F6",
    description: "Travel, transport, and the world outside",
    words: [
      { persian: "هواپیما", phonetic: "Hava-Peyma", english: "Airplane (lit: something that flies in air)", example: "با هواپیما رفتم." },
      { persian: "قطار", phonetic: "Ghatar", english: "Train", example: "قطار دیر کرد." },
      { persian: "ماشین", phonetic: "Maashin", english: "Car", example: "ماشینم تو پارکینگه." },
      { persian: "تاکسی", phonetic: "Taaksi", english: "Taxi", example: "تاکسی گرفتم." },
      { persian: "هوا", phonetic: "Hava", english: "Air / Weather", example: "هوا سرده امروز." },
      { persian: "آسمون", phonetic: "Asemoon", english: "Sky", example: "آسمون آبیه." },
      { persian: "کشور", phonetic: "Keshvar", english: "Country", example: "کشور قشنگیه." },
      { persian: "شهر", phonetic: "Shahr", english: "City", example: "این شهر بزرگه." },
      { persian: "خیابان", phonetic: "Khiyaabaan", english: "Street", example: "خیابان شلوغه." },
      { persian: "فرودگاه", phonetic: "Forudgaah", english: "Airport", example: "فرودگاه کجاست؟" },
    ],
  },
  {
    id: "clothing",
    title: "Clothing",
    icon: "👕",
    color: "#FF9600",
    description: "What to wear",
    words: [
      { persian: "لباس", phonetic: "Lebaas", english: "Clothes / Outfit", example: "لباس قشنگی پوشیدی." },
      { persian: "پیرهن", phonetic: "Pirhan", english: "Shirt", example: "پیرهن آبی می‌خوام." },
      { persian: "شلوار", phonetic: "Shalvaar", english: "Pants", example: "شلوارم کجاست؟" },
      { persian: "کت", phonetic: "Kot", english: "Coat / Jacket", example: "کتم رو بیار." },
      { persian: "کفش", phonetic: "Kafsh", english: "Shoes", example: "کفشام نو هستن." },
      { persian: "جوراب", phonetic: "Jooraab", english: "Socks", example: "جورابم گم شد." },
      { persian: "کلاه", phonetic: "Kolaah", english: "Hat", example: "کلاه سرت بذار." },
      { persian: "کیف", phonetic: "Kif", english: "Bag / Purse", example: "کیفم رو دیدی؟" },
      { persian: "عینک", phonetic: "Eynak", english: "Glasses", example: "عینکم رو نمی‌بینم." },
      { persian: "ساعت", phonetic: "Sâat", english: "Watch / Clock / Hour", example: "ساعت چنده؟" },
    ],
  },
  {
    id: "days",
    title: "Days of the Week",
    icon: "📅",
    color: "#58CC02",
    description: "Days, months, and time expressions",
    words: [
      { persian: "شنبه", phonetic: "Shanbe", english: "Saturday", example: "شنبه تعطیله." },
      { persian: "یکشنبه", phonetic: "Yekshanbe", english: "Sunday", example: "یکشنبه بریم؟" },
      { persian: "دوشنبه", phonetic: "Doshanbe", english: "Monday", example: "دوشنبه کلاس دارم." },
      { persian: "سه‌شنبه", phonetic: "Seshanbe", english: "Tuesday", example: "سه‌شنبه می‌ام." },
      { persian: "چهارشنبه", phonetic: "Chahaarshanbe", english: "Wednesday", example: "چهارشنبه جلسه دارم." },
      { persian: "پنجشنبه", phonetic: "Panjshanbe", english: "Thursday", example: "پنجشنبه آزادم." },
      { persian: "جمعه", phonetic: "Jom'e", english: "Friday", example: "جمعه تعطیله." },
      { persian: "امروز", phonetic: "Emruz", english: "Today", example: "امروز خوبه." },
      { persian: "فردا", phonetic: "Fardaa", english: "Tomorrow", example: "فردا می‌بینمت." },
      { persian: "دیروز", phonetic: "Diruz", english: "Yesterday", example: "دیروز رفتم." },
      { persian: "هفته", phonetic: "Hafte", english: "Week", example: "این هفته مشغولم." },
      { persian: "ماه", phonetic: "Maah", english: "Month / Moon", example: "این ماه بریم." },
    ],
  },
  {
    id: "verbs",
    title: "Essential Verbs",
    icon: "⚡",
    color: "#CE82FF",
    description: "Action words to get started",
    words: [
      { persian: "رفتن", phonetic: "Raftan", english: "To go", example: "می‌خوام برم." },
      { persian: "آمدن", phonetic: "Aamadan", english: "To come", example: "بیا اینجا." },
      { persian: "خوردن", phonetic: "Khordan", english: "To eat", example: "چی می‌خوری؟" },
      { persian: "نوشیدن", phonetic: "Nushidan", english: "To drink", example: "آب می‌نوشم." },
      { persian: "خواندن", phonetic: "Khaandan", english: "To read / To sing", example: "کتاب می‌خونم." },
      { persian: "نوشتن", phonetic: "Neveshtan", english: "To write", example: "نامه می‌نویسم." },
      { persian: "دیدن", phonetic: "Didan", english: "To see", example: "فیلم می‌بینم." },
      { persian: "شنیدن", phonetic: "Shenidan", english: "To hear / To listen", example: "موزیک می‌شنوم." },
      { persian: "دانستن", phonetic: "Dânestan", english: "To know", example: "نمی‌دونم." },
      { persian: "گفتن", phonetic: "Goftan", english: "To say / To tell", example: "چی گفتی؟" },
      { persian: "خوابیدن", phonetic: "Khaabidan", english: "To sleep", example: "می‌خوام بخوابم." },
      { persian: "بودن", phonetic: "Budan", english: "To be", example: "کجایی؟" },
    ],
  },
  {
    id: "slang",
    title: "Slang & Adult Words",
    icon: "🔞",
    color: "#FF4B4B",
    description: "Colorful language — you've been warned!",
    words: [
      { persian: "کون", phonetic: "Koon", english: "Ass / Butt", example: "درد کونم اومد." },
      { persian: "کیر", phonetic: "Kir", english: "Cock / Dick", example: "— (explicit)" },
      { persian: "کس", phonetic: "Kos", english: "Pussy", example: "— (explicit)" },
      { persian: "گه", phonetic: "Goh", english: "Shit", example: "گه خوردی! (You messed up!)" },
      { persian: "خفه شو", phonetic: "Khaffe sho", english: "Shut up!", example: "خفه شو، حوصله ندارم." },
      { persian: "دیوونه", phonetic: "Divooneh", english: "Crazy / Insane", example: "دیوونه شدی؟!" },
      { persian: "بی‌شعور", phonetic: "Bisho'oor", english: "Idiot (lit: without sense)", example: "چه آدم بی‌شعوریه." },
      { persian: "مزخرف", phonetic: "Mazakhraf", english: "Nonsense / Crap", example: "مزخرف نگو." },
      { persian: "ولش کن", phonetic: "Valesh kon", english: "Drop it / Forget it", example: "ولش کن، ارزش نداره." },
      { persian: "بیخود", phonetic: "Bikhod", english: "For no reason / In vain", example: "بیخود اومدی." },
    ],
  },
];

const XP_PER_LESSON = 10;
const HEARTS_MAX = 5;

// Node.js compatibility (used by generate-audio.js)
if (typeof module !== "undefined") module.exports = { LESSONS };
