const LESSONS = [
  {
    id: "greetings",
    title: "Greetings",
    icon: "👋",
    color: "#58CC02",
    description: "Say hello and be polite",
    words: [
      { persian: "سلام", phonetic: "Salâm", english: "Hello", example: "سلام! چطوری؟" },
      { persian: "خداحافظ", phonetic: "Khodâhâfez", english: "Goodbye", example: "خداحافظ! فردا می‌بینمت." },
      { persian: "ممنون", phonetic: "Mamnun", english: "Thank you", example: "ممنون از کمکت." },
      { persian: "خواهش می‌کنم", phonetic: "Khâhesh mikonam", english: "You're welcome", example: "خواهش می‌کنم، مشکلی نیست." },
      { persian: "بله", phonetic: "Bale", english: "Yes", example: "بله، درسته." },
      { persian: "نه", phonetic: "Na", english: "No", example: "نه، ممنون." },
      { persian: "ببخشید", phonetic: "Bebakhshid", english: "Excuse me / Sorry", example: "ببخشید، می‌تونید کمک کنید؟" },
      { persian: "لطفاً", phonetic: "Lotfan", english: "Please", example: "لطفاً صبر کنید." },
      { persian: "چطوری؟", phonetic: "Chetori?", english: "How are you? (informal)", example: "سلام! چطوری؟" },
      { persian: "خوبم", phonetic: "Khubam", english: "I'm good", example: "خوبم، ممنون." },
      { persian: "اسمت چیه؟", phonetic: "Esmat chiye?", english: "What's your name?", example: "سلام! اسمت چیه؟" },
      { persian: "اسمم ... است", phonetic: "Esmam ... ast", english: "My name is...", example: "اسمم آلینا است." },
    ],
  },
  {
    id: "numbers",
    title: "Numbers",
    icon: "🔢",
    color: "#FF9600",
    description: "Count from 1 to 10",
    words: [
      { persian: "یک", phonetic: "Yek", english: "One", example: "یک سیب دارم." },
      { persian: "دو", phonetic: "Do", english: "Two", example: "دو تا بده." },
      { persian: "سه", phonetic: "Se", english: "Three", example: "سه روز دیگه." },
      { persian: "چهار", phonetic: "Chahâr", english: "Four", example: "چهار نفر اومدن." },
      { persian: "پنج", phonetic: "Panj", english: "Five", example: "پنج دقیقه صبر کن." },
      { persian: "شش", phonetic: "Shesh", english: "Six", example: "شش ماه گذشت." },
      { persian: "هفت", phonetic: "Haft", english: "Seven", example: "هفت روز هفته." },
      { persian: "هشت", phonetic: "Hasht", english: "Eight", example: "هشت ساعت خوابیدم." },
      { persian: "نه", phonetic: "Noh", english: "Nine", example: "نه نفر بودیم." },
      { persian: "ده", phonetic: "Dah", english: "Ten", example: "ده تومن." },
      { persian: "بیست", phonetic: "Bist", english: "Twenty", example: "بیست سال دارم." },
      { persian: "صد", phonetic: "Sad", english: "One hundred", example: "صد تا بخر." },
    ],
  },
  {
    id: "colors",
    title: "Colors",
    icon: "🎨",
    color: "#CE82FF",
    description: "Learn all the colors",
    words: [
      { persian: "قرمز", phonetic: "Qermez", english: "Red", example: "گل قرمز زیباست." },
      { persian: "آبی", phonetic: "Âbi", english: "Blue", example: "آسمان آبیه." },
      { persian: "سبز", phonetic: "Sabz", english: "Green", example: "درخت سبزه." },
      { persian: "زرد", phonetic: "Zard", english: "Yellow", example: "خورشید زرده." },
      { persian: "سفید", phonetic: "Sefid", english: "White", example: "برف سفیده." },
      { persian: "مشکی", phonetic: "Meshki", english: "Black", example: "شب مشکیه." },
      { persian: "نارنجی", phonetic: "Nârenji", english: "Orange", example: "پرتقال نارنجیه." },
      { persian: "بنفش", phonetic: "Banafsh", english: "Purple", example: "گل بنفشه." },
      { persian: "صورتی", phonetic: "Surati", english: "Pink", example: "لباس صورتیه." },
      { persian: "قهوه‌ای", phonetic: "Qahve'i", english: "Brown", example: "خاک قهوه‌اییه." },
      { persian: "خاکستری", phonetic: "Khâkestari", english: "Gray", example: "ابر خاکستریه." },
    ],
  },
  {
    id: "family",
    title: "Family",
    icon: "👨‍👩‍👧",
    color: "#FF4B4B",
    description: "Talk about your family",
    words: [
      { persian: "مادر", phonetic: "Mâdar", english: "Mother", example: "مادرم خوبه." },
      { persian: "پدر", phonetic: "Pedar", english: "Father", example: "پدرم کار می‌کنه." },
      { persian: "خواهر", phonetic: "Khâhar", english: "Sister", example: "خواهرم دانشجوئه." },
      { persian: "برادر", phonetic: "Barâdar", english: "Brother", example: "برادرم بزرگه." },
      { persian: "دختر", phonetic: "Dokhtar", english: "Daughter / Girl", example: "دختر کوچیک." },
      { persian: "پسر", phonetic: "Pesar", english: "Son / Boy", example: "پسر باهوشیه." },
      { persian: "مادربزرگ", phonetic: "Mâdarbozorg", english: "Grandmother", example: "مادربزرگم مهربونه." },
      { persian: "پدربزرگ", phonetic: "Pedarbozorg", english: "Grandfather", example: "پدربزرگم قصه می‌گه." },
      { persian: "عمو", phonetic: "Amu", english: "Uncle (paternal)", example: "عموم تهرانه." },
      { persian: "خاله", phonetic: "Khâle", english: "Aunt (maternal)", example: "خاله‌ام دکتره." },
      { persian: "عمه", phonetic: "Amme", english: "Aunt (paternal)", example: "عمه‌ام خوشگله." },
      { persian: "دایی", phonetic: "Dâyi", english: "Uncle (maternal)", example: "دایی‌ام مهندسه." },
    ],
  },
  {
    id: "food",
    title: "Food & Drink",
    icon: "🍽️",
    color: "#1CB0F6",
    description: "Essential food vocabulary",
    words: [
      { persian: "نان", phonetic: "Nân", english: "Bread", example: "نان تازه می‌خوام." },
      { persian: "آب", phonetic: "Âb", english: "Water", example: "آب بده لطفاً." },
      { persian: "چای", phonetic: "Châi", english: "Tea", example: "چای می‌خوری؟" },
      { persian: "برنج", phonetic: "Berenj", english: "Rice", example: "برنج ایرانی خوشمزه‌ست." },
      { persian: "مرغ", phonetic: "Morgh", english: "Chicken", example: "مرغ کباب کردیم." },
      { persian: "گوشت", phonetic: "Gusht", english: "Meat", example: "گوشت گرونه." },
      { persian: "میوه", phonetic: "Mive", english: "Fruit", example: "میوه می‌خوری؟" },
      { persian: "سبزی", phonetic: "Sabzi", english: "Herbs / Vegetables", example: "سبزی پلو خوشمزه‌ست." },
      { persian: "پنیر", phonetic: "Panir", english: "Cheese", example: "پنیر و نان." },
      { persian: "تخم مرغ", phonetic: "Tokhm-e morgh", english: "Egg", example: "تخم مرغ آب‌پز." },
      { persian: "قهوه", phonetic: "Qahve", english: "Coffee", example: "قهوه یا چای؟" },
      { persian: "شیر", phonetic: "Shir", english: "Milk", example: "شیر گرم بده." },
    ],
  },
  {
    id: "days",
    title: "Days of the Week",
    icon: "📅",
    color: "#FF9600",
    description: "Days and time expressions",
    words: [
      { persian: "شنبه", phonetic: "Shanbe", english: "Saturday", example: "شنبه تعطیله." },
      { persian: "یکشنبه", phonetic: "Yekshanbe", english: "Sunday", example: "یکشنبه بریم؟" },
      { persian: "دوشنبه", phonetic: "Doshanbe", english: "Monday", example: "دوشنبه کلاس دارم." },
      { persian: "سه‌شنبه", phonetic: "Seshanbe", english: "Tuesday", example: "سه‌شنبه می‌ام." },
      { persian: "چهارشنبه", phonetic: "Chahârshanbe", english: "Wednesday", example: "چهارشنبه جلسه دارم." },
      { persian: "پنجشنبه", phonetic: "Panjshanbe", english: "Thursday", example: "پنجشنبه آزادم." },
      { persian: "جمعه", phonetic: "Jom'e", english: "Friday", example: "جمعه تعطیله." },
      { persian: "امروز", phonetic: "Emruz", english: "Today", example: "امروز خوبه." },
      { persian: "فردا", phonetic: "Fardâ", english: "Tomorrow", example: "فردا می‌بینمت." },
      { persian: "دیروز", phonetic: "Diruz", english: "Yesterday", example: "دیروز رفتم." },
      { persian: "هفته", phonetic: "Hafte", english: "Week", example: "این هفته مشغولم." },
      { persian: "ماه", phonetic: "Mâh", english: "Month / Moon", example: "این ماه بریم." },
    ],
  },
  {
    id: "verbs",
    title: "Essential Verbs",
    icon: "⚡",
    color: "#58CC02",
    description: "Action words to get started",
    words: [
      { persian: "رفتن", phonetic: "Raftan", english: "To go", example: "می‌خوام برم." },
      { persian: "آمدن", phonetic: "Âmadan", english: "To come", example: "بیا اینجا." },
      { persian: "خوردن", phonetic: "Khordan", english: "To eat", example: "چی می‌خوری؟" },
      { persian: "نوشیدن", phonetic: "Nushidan", english: "To drink", example: "آب می‌نوشم." },
      { persian: "خواندن", phonetic: "Khândan", english: "To read / To sing", example: "کتاب می‌خونم." },
      { persian: "نوشتن", phonetic: "Neveshtan", english: "To write", example: "نامه می‌نویسم." },
      { persian: "دیدن", phonetic: "Didan", english: "To see", example: "فیلم می‌بینم." },
      { persian: "شنیدن", phonetic: "Shenidan", english: "To hear / To listen", example: "موزیک می‌شنوم." },
      { persian: "دانستن", phonetic: "Dânestan", english: "To know", example: "نمی‌دونم." },
      { persian: "گفتن", phonetic: "Goftan", english: "To say / To tell", example: "چی گفتی؟" },
      { persian: "خوابیدن", phonetic: "Khâbidan", english: "To sleep", example: "می‌خوام بخوابم." },
      { persian: "بودن", phonetic: "Budan", english: "To be", example: "کجایی؟" },
    ],
  },
  {
    id: "phrases",
    title: "Useful Phrases",
    icon: "💬",
    color: "#CE82FF",
    description: "Essential everyday phrases",
    words: [
      { persian: "نمی‌فهمم", phonetic: "Nemifahmam", english: "I don't understand", example: "ببخشید، نمی‌فهمم." },
      { persian: "می‌فهمم", phonetic: "Mifahmam", english: "I understand", example: "بله، می‌فهمم." },
      { persian: "تکرار کن", phonetic: "Tekrâr kon", english: "Repeat please", example: "می‌شه تکرار کنی؟" },
      { persian: "آهسته‌تر", phonetic: "Âheste-tar", english: "Slower please", example: "آهسته‌تر صحبت کن." },
      { persian: "فارسی بلدی؟", phonetic: "Fârsi boladi?", english: "Do you know Persian?", example: "فارسی بلدی؟" },
      { persian: "کمی فارسی بلدم", phonetic: "Kami Fârsi baladam", english: "I know a little Persian", example: "کمی فارسی بلدم." },
      { persian: "کجاست؟", phonetic: "Kojâst?", english: "Where is it?", example: "دستشویی کجاست؟" },
      { persian: "چقدر؟", phonetic: "Cheghadr?", english: "How much?", example: "این چقدره؟" },
      { persian: "دوستت دارم", phonetic: "Dustat dâram", english: "I love you", example: "مامان، دوستت دارم." },
      { persian: "خوش آمدید", phonetic: "Khosh âmadid", english: "Welcome", example: "به ایران خوش آمدید." },
      { persian: "موفق باشی", phonetic: "Movaffaq bâshi", english: "Good luck", example: "موفق باشی در امتحان." },
      { persian: "نوش جان", phonetic: "Nush-e jân", english: "Bon appétit / Enjoy your meal", example: "نوش جان!" },
    ],
  },
];

const XP_PER_LESSON = 10;
const HEARTS_MAX = 5;
